# Generated by Django 5.1.5 on 2025-01-23 17:23

import django.core.validators
import django.db.models.deletion
import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0007_class_active_session_attendancesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the lesson', null=True)),
                ('pdf_content', models.FileField(blank=True, help_text='Upload PDF material for the lesson', null=True, upload_to=lessons.models.pdf_upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf'])])),
                ('video_content', models.FileField(blank=True, help_text='Upload video recording of the session', null=True, upload_to=lessons.models.video_upload_path, validators=[django.core.validators.FileExtensionValidator(['mp4', 'webm', 'mkv'])])),
                ('video_summary', models.TextField(blank=True, help_text='AI-generated summary of the video content', null=True)),
                ('has_simulation', models.BooleanField(default=False)),
                ('simulation_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='classes.class')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
                'ordering': ['-created_at'],
            },
        ),
    ]
