# Generated by Django 5.1.5 on 2025-01-23 21:55

import django.core.validators
import lessons.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='has_3d_model',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lesson',
            name='model_file',
            field=models.FileField(blank=True, help_text='Upload 3D model file (GLB format)', null=True, upload_to=lessons.models.model_upload_path, validators=[django.core.validators.FileExtensionValidator(['glb', 'gltf'])]),
        ),
        migrations.AddField(
            model_name='lesson',
            name='model_poster',
            field=models.ImageField(blank=True, help_text='Upload poster image for 3D model', null=True, upload_to=lessons.models.model_upload_path),
        ),
    ]
