# Generated by Django 4.2 on 2025-01-23 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_enrollment'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrolled_classes',
            field=models.ManyToManyField(related_name='enrolled_students', through='classes.Enrollment', to='classes.class'),
        ),
    ]
