# Generated by Django 5.1.5 on 2025-01-23 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_attendance_total_sessions'),
        ('students', '0002_student_enrolled_classes'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='active_session',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AttendanceSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField(default=False)),
                ('class_instance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_attendance', to='classes.class')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.student')),
            ],
            options={
                'unique_together': {('class_instance', 'student')},
            },
        ),
    ]
